image: python:3.7
pipelines:
  default:
  - step:
      name: install pipenv, django, pytest-django, and test djangodemo
      script:
          - export PIP_CACHE_DIR=.cache/pip
          - pip install pipenv
          - pipenv install
          - pipenv install Django
          - pipenv install pytest-django
          - pip install pipenv
          - pipenv run pytest --junitxml=test-results/junit.xml djangodemo/tests
      caches:
          - pip

