version: 0.2

env:
  variables:
    PIPENV_VENV_IN_PROJECT: "true"

phases:
  build:
    commands:
      - echo Entered the build phase...
      - apt update
      - pip install --upgrade pip
      - pip install pipenv
      - pipenv install
      - pipenv install Django==2.0
      - pipenv install pytest-django
      - pipenv run pytest --junitxml=test-results/junit.xml djangodemo/tests
      - python djangodemo/setup.py sdist
    finally:
      - echo Build phase complete
artifacts:
  files:
    - djangodemo/*.egg-info
  cache:
    paths:
      - '/root/.cache/pip'
